services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./create_programming_task:/usr/src/app
    stdin_open: true
    tty: true
